# Generated by Django 4.2 on 2025-02-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Name')),
                ('price', models.IntegerField(verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Мерч',
                'verbose_name_plural': 'Мерчи',
            },
        ),
    ]
